### ISSUE TITLE
Git clone link in INSTALL.md

### ISSUE THREAD

**Issue by mcmellow** [avollkopf/iSpindel-TCP-Server#10]
Hi,

Your INSTALL.md is pointing to another repo.

git clone https://github.com/DottoreTozzi/iSpindel-TCP-Server iSpindel-Srv

I guess this should be: 
git clone https://github.com/avollkopf/iSpindel-TCP-Server iSpindel-Srv

Regards,
McMelloW

**Comment by avollkopf** [comment]
Hi Mellow,

at this point of time I have upadted only the english version of the install instructions. There I am referring to my repo.

The update of the german version will follow this weekend.

Regards,
Alex

**Comment by avollkopf** [comment]
Updated also the Install.md file

**Comment by mcmellow** [comment]
Alex,

I will do a scratch install on a spare Raspberry Pi 3B+ coming weeks to see how it works. Does it works on an aarch64 RPi-OS?

**Comment by avollkopf** [comment]
Hi Mellow, this should work. The server itself has not changed. You just need to have a running web server, sql and python on the pi.
