### ISSUE TITLE
Only 2 pages can be seen. Everything else is missing

### ISSUE THREAD

**Issue by jsbjx** [avollkopf/iSpindel-TCP-Server#11]
（2020_12_iSpindle_TCP_Server_rev2） Only two pages can be displayed after installation. Nothing else can be seen. Download [（iSpindel-TCP-Server-master]([url]([url](url)))  3.1 ）and install the same result. What is the reason?

![11](https://user-images.githubusercontent.com/32890201/102044848-aeec7e80-3e12-11eb-8031-1d01a2bcca28.png)
![22](https://user-images.githubusercontent.com/32890201/102044874-b7dd5000-3e12-11eb-9c56-93d149d10889.png)

**Comment by avollkopf** [comment]
What if you go to the TCP Server Settings? This should work and there you could also find settings to switch to english if this is your preferred language.

How many datapoints did you transfer from you Spindle to the server?

**Comment by jsbjx** [comment]
![33](https://user-images.githubusercontent.com/32890201/102050616-1fe56380-3e1e-11eb-9ce6-898c7f13cd48.png)
Click “"TCP Server Settings Editieren", but the content is missing. "Switch to English settings" window not found, please check the picture

**Comment by jsbjx** [comment]
[1.zip](https://github.com/avollkopf/iSpindel-TCP-Server/files/5687106/1.zip)

**Comment by avollkopf** [comment]
Well, this is the settings page. Did you walk through the pull down menus? You will find it there under GENERAL.

And please don't upload files w/o any sort of explanation. I won't open them. 

And please answer the question related to the data that has been transferred by a spindle I asked in my first response.

**Comment by jsbjx** [comment]
“And please answer the question related to the data that has been transferred by a spindle I asked in my first response.”
I did not find a page to add a device. So I can't connect the  iSpindel to server, I want to make a video for you. How to pass it to you?

**Comment by avollkopf** [comment]
There is no need to do anything on the iSpindle server side. You need  to configure your iSpindle to transfer data to the IP Address of your server, Port 9501. The device will be added automatically on the server side.

**Comment by jsbjx** [comment]
Thank you for your guidance. I can already see iSpindle displayed on the server interface. I can also see the language selection. But I still can’t find the language menu to add new languages, and the icon of "house" in the upper left corner of the page cannot be displayed

**Comment by avollkopf** [comment]
Hi, The icon for home is not nicluded in the image which is related to licensing for those images. I am allowed to use them but I cannot distribute it.

You just need to place an image with the name 'icons8-home-26.png' in the  iSpindle-Srv/web/include directory of the server

There is no language menu to add new languages to the server.

This has to be handled through the settings and strings table of the database. It can be done via phpmyadmin which is included in the image.

If you want to add for instance Chinese language, you need to add a column 'Description_CN' to he end of the Strings table (type: varchar(1024) )

Then just add all the descriptions in chinese to this column

Do the same thing for the settings table but add the column 'Description_CN' BEFORE the DeviceName column

Afterwards, you can set the language to CN in the settings menu and the columns Description_CN are used for the server. However, You may need to change also the default locales via the raspi-config to the correct charset/keyboard settings.

If the languega would be for instance Japanese, The columns should have the Name Description_JP.... In this case JP would need to be entered in the settings for Language.

**Comment by jsbjx** [comment]
Thank you for your patient answer. I made an iSpindle (static power consumption of 0.1mA, which is more power efficient than the original 3 modules iSpindle (static power consumption of 3.8mA). It greatly extends the use time or can transmit more signals in the same time.

**Comment by avollkopf** [comment]
ok, i consider this issue as closed
