### ISSUE TITLE
Field 'const0' doesn't have a default value

### ISSUE THREAD

**Issue by Wim-T** [avollkopf/iSpindel-TCP-Server#12]
After installing image "2021_01_iSpindle_TCP_Server.img" on a 16GB SD-card, the TCP Server seems to run well on my Raspberry Pi 3B. The web interface works well. All data, sent by my iSpindel, are nicely collected in the database and can be displayed in graphs.

Except one thing. Calibration of the constants does not work.
When I press button "Spindle im TCP Server kalibrieren", I get this page for the calibration;
![calibration page](https://user-images.githubusercontent.com/13780931/104072581-d82edd80-520b-11eb-94e7-ee691b05c761.png)
After typing the values of the constants and pressing "Kalibrierung an DB senden", I first get the confirmation window "Kalibrierung an Datenbak gesendet!" and next this error message:
**Field 'const0' doesn't have a default value**

Without calibration, some of the graphs cannot be displayed.
I did not make any changes after installing the image.
I hope you can help me to solve this issue.
Thanks in advance.

**Comment by avollkopf** [comment]
Hi, I will look into thatz as it is working on my side. What value did you use for const0? Theoretically, a zero should work.

**Comment by Wim-T** [comment]
Hi, it does not matter what values I fill out in the 4 fields for the constants (zero's or the actual values I want to use), after pressing "Kalibrierung an DB senden" I get the small confirmation window with "Kalibrierung an Datenbank gesendet!" and when I press OK in that window a new page opens with that message: **Field 'const0' doesn't have a default value**.

Searching on internet, I found this website:
 [https://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values](url). 
Unfortunately I am not very familiar with PHP and MySQL, but maybe it is helpful for you.

**Comment by avollkopf** [comment]
That should have been already fixed in the database. Could be done easily via phpmyadmin. But I will look into it. I have checked it only on my system that is running in a contaner on my NAS. I will bottle my current beer today and afterwards I can insert the test SD card into my Raspi.

I will set the default values for all the consts to 0. But what you are reporting seems to be another issue in addition to that.

**Comment by avollkopf** [comment]
Hi, I have added a fix for this. You need to log in to your raspi, and go to the ispindle server directory ad run sudo ./update-raspi.sh.

This will update the files index.php and common_db_query.php.

When access the index page, the script is checking if default values are defined for the calibration table. If not, the table will be changed with default values of 0. This worked on my raspi image.

I won't be able to provide a new image, but this should do the trick. Please report back if we can close the issue.

**Comment by Wim-T** [comment]
Hi, I ran the update, and it also works on my raspberry image.
It is possible now to show all graphs, so you can close the issue.
Thanks very much for the quick repair !!
