### ISSUE TITLE
Boot to terminal after install

### ISSUE THREAD

**Issue by thomaspburrows** [avollkopf/iSpindel-TCP-Server#14]
Hi, not a problem as such. More of a question. I just set this up on a new Raspberry Pi. All seems to be working with the site. Still to build the iSpindle so will be a little while before I test with that. After install is it deisgned to boot the RaspPi to the terminal? I am unable to get it to boot to the Desktop since install. Thanks

**Comment by avollkopf** [comment]
Hi, you are right, this is a headless version. I am basivally running this on a NAS in a virtual environment. Only once in a while I can create an image on a raspberry. However, my Raspberry is mounted in my brew controller w/o scren, keyboard,... That is the reason why I cannot provide/test the full rasbian incl. Desktop.

**Comment by thomaspburrows** [comment]
Hi, thanks for explaining. I am happy to SSH in and run it as a headless install as it is the only thing I plan on using the Raspberry for at the moment. Is it still possible to display the graphs on a Raspi touch display connected directly to the Raspi?

**Comment by avollkopf** [comment]
I don't think that you can display graphs. Most likely you need to follow these instructions to enable a graphical UI: https://raspberrytips.com/upgrade-raspbian-lite-to-desktop/

**Comment by thomaspburrows** [comment]
Ah OK. So to be clear, I had the GUI already with PIXEL. After installing RasPySpindel it stripped it back to headless. I can upgrade again to enable a GUI of my choosing and it shouldn't affect RasPySpindel functionality?

**Comment by avollkopf** [comment]
I assume you've installed the image. This will completely erase the existing system. If you upgrade via the described way, the server should be still running. However, you should back up your system first.

You could also install the full raspbian incl. desktop and follow the installation instructions for the raspi,

**Comment by thomaspburrows** [comment]
I followed https://github.com/avollkopf/iSpindel-TCP-Server/blob/master/INSTALL_en_Raspi.md from a full RasPi system. I can try and upgrade and see if it works. The other thing I wondered was if the SD is corrupt and that is why it wont boot back to Desktop. Although I would have expected it to just not boot in that case. I will attempt the upgrade, worst case scenario I can format and begin again as I havent set up the iSpindle yet.

**Comment by thomaspburrows** [comment]
Back in action after reinstalling PIXEL with sudo apt install raspberrypi-ui-mods and all still seems good with the RasPySpindel. Thanks for your help
