### ISSUE TITLE
PHP error messages.

### ISSUE THREAD

**Issue by francoisduprez** [avollkopf/iSpindel-TCP-Server#15]
When opening plato4.php for example i get these errors:

Deprecated: Required parameter $filename follows optional parameter $table in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 520
Deprecated: Required parameter $filename follows optional parameter $table in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 544
Deprecated: Required parameter $lasttime follows optional parameter $iSpindleID in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 1651
Deprecated: Required parameter $hours follows optional parameter $iSpindleID in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 1651
Deprecated: Required parameter $movingtime follows optional parameter $iSpindleID in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 1844

same with angle.php

Deprecated: Required parameter $filename follows optional parameter $table in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 520
Deprecated: Required parameter $filename follows optional parameter $table in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 544
Deprecated: Required parameter $lasttime follows optional parameter $iSpindleID in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 1651
Deprecated: Required parameter $hours follows optional parameter $iSpindleID in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 1651
Deprecated: Required parameter $movingtime follows optional parameter $iSpindleID in /srv/http/iSpindel-Srv/web/include/common_db_query.php on line 1844

Everything is working fine. Only the errors.

Running om Manjaro with PHP 8.0.5

**Comment by avollkopf** [comment]
Thanks for the heads up. I will need to look ino that and what will be changed between php7 and 8. Maybe I can solve it w/o php8. Otherwise I need to set up a test system in a container which may take some time.

EDIT: I think, only minor changes are required but I need to ensure there is no impact to php 7. I guess I will have a version by end of this week.

**Comment by francoisduprez** [comment]
> Thanks for the heads up. I will need to look ino that and what will be changed between php7 and 8. Maybe I can solve it w/o php8. Otherwise I need to set up a test system in a container which may take some time.
> 
> EDIT: I think, only minor changes are required but I need to ensure there is no impact to php 7. I guess I will have a version by end of this week.

Thanks for the quick response. 
I'm not in a hurry, it's working fine appart from the errors on the screen.. :)

**Comment by avollkopf** [comment]
Hi, I was able to install php 8.0.5 in my ubuntu 16.04 container. Unfortunately, the system did not show any of the errors that should be shown with php 8 and optional varaibles....

Anyhow, I changed a few things that should address the error messages. It would be great, if you could test it. You just need to unzip the common_db_query.php and copy it to ....web/include. I recommend to rename the existing file first to revert it back in case of an issue. But the modified version is working on my system.

[common_db_query.zip](https://github.com/avollkopf/iSpindel-TCP-Server/files/6454026/common_db_query.zip)

If it is also working on your system, I can update the repo.

EDIT:
Just looked into the php.ini and changed the error reporting to E_ALL. I was able to reproduce the error and with the zipped version, I cannot find an error. Once you report back that you also have no issues, I will update the repo.

**Comment by francoisduprez** [comment]
> Hi, I was able to install php 8.0.5 in my ubuntu 16.04 container. Unfortunately, the system did not show any of the errors that should be shown with php 8 and optional varaibles....
> 
> Anyhow, I changed a few things that should address the error messages. It would be great, if you could test it. You just need to unzip the common_db_query.php and copy it to ....web/include. I recommend to rename the existing file first to revert it back in case of an issue. But the modified version is working on my system.
> 
> [common_db_query.zip](https://github.com/avollkopf/iSpindel-TCP-Server/files/6454026/common_db_query.zip)
> 
> If it is also working on your system, I can update the repo.
> 
> EDIT:
> Just looked into the php.ini and changed the error reporting to E_ALL. I was able to reproduce the error and with the zipped version, I cannot find an error. Once you report back that you also have no issues, I will update the repo.

Works like a charm, no errors anymore. 

Thanks, great job....

**Comment by avollkopf** [comment]
Issue has been solved with commit from 11.05.21 (https://github.com/avollkopf/iSpindel-TCP-Server/commit/0a6c6279f29d61cab79b43b82c4f36e8d23d8f2a)
