### ISSUE TITLE
Connect-method for database may not exist anymore in mysql.connector in latest version

### ISSUE THREAD

**Issue by Bowly72** [avollkopf/iSpindel-TCP-Server#21]
According to the description I installed everything on a Raspberry Pi 4. The website was working but no data were transfered from the iSpindle to the database. I used the latest version of the mysql.connector as well as of the MariaDB. During debugging I found out, that in iSpindle.py it hangs in the loop where it connects to the database and the error message tells about that missing connect() method. So I replaced the namespace "mysql.connector" with "mariadb" in the whole code of iSpindle.py and sendmail.py and it worked. I'm not sure, if that is a generally usable solution. That's why i did not make a branch yet. What do you think?

**Comment by avollkopf** [comment]
For now, it could be fixed if the mysql connector version is limited to 8.0.29

`sudo pip3 install mysql-connector-python==8.0.29`

In this case, no change of the code is required -> UTF-8 error is prevented which is caused in version > 8.0.29 in combination with mariadb. 

If code is changed, it should be flexible for mysql and mariadb. Nor sure if mariadb connect can handle both databases

**Comment by avollkopf** [comment]
should be addressed with latest change of instructions
