### ISSUE TITLE
Data Column Recipe_ID und Table Archive

### ISSUE THREAD

**Issue by ollinator2000** [avollkopf/iSpindel-TCP-Server#4]
Kann es sein , das bei einer Initialen Installation die Anlage der Spalte Recipe_ID sowie des Tables Archive fehlt ? 
Ich baue gerade an einer vereinfachten Installation , aber deinen Fork bekommen ich noch nicht zum fliegen .. ;-) 

' in 'field list'
Did you update your database?
...connected from: ('172.19.0.1', 54720)
waiting for connection... listening on port: 9501
('172.19.0.1', 54720) received:'{'
('172.19.0.1', 54720) Input Str is now:{
sh: 1: /usr/local/bin/sendmail.py: not found
('172.19.0.1', 54720) received:'"name":"iSpindel","ID":3766317,"angle":7.678458,"temperature":23.9375,"temp_units":"C","battery":4.092805,"gravity":-4.918264,"interval":900,"RSSI":-37}\r\n'
('172.19.0.1', 54720) Input Str is now:{"name":"iSpindel","ID":3766317,"angle":7.678458,"temperature":23.9375,"temp_units":"C","battery":4.092805,"gravity":-4.918264,"interval":900,"RSSI":-37}
('172.19.0.1', 54720) Sent ACK.
('172.19.0.1', 54720) Time elapsed: 0.003094
('172.19.0.1', 54720) iSpindel (ID:3766317) : Data Transfer OK.
('172.19.0.1', 54720) - closed connection
('172.19.0.1', 54720) Reading last recipe name for corresponding SpindeliSpindel
('172.19.0.1', 54720) Recipe Name not found - Database Error: 'NoneType' object has no attribute '__getitem__'
('172.19.0.1', 54720) Reading last recipe_id value for corresponding SpindeliSpindel
('172.19.0.1', 54720) Recipe_ID not found - Database Error: 1146 (42S02): Table 'iSpindle.Archive' doesn't exist
('172.19.0.1', 54720) - writing to database
('172.19.0.1', 54720) Database Error: 1054 (42S22): Unknown column 'Recipe_ID' in 'field list'
Did you update your database?

**Comment by avollkopf** [comment]
Das ist korrekt. Die integrierte Migration basiert auf der alten Tabelle.

Ich hätte mich als nächstes auch an ein Script gemacht, dass die Datenbank aufsetzt. Aber Prio hatte das Archiv und die Anpassung der Python Scripte auf Python3.

Ich kann später mal die Struktur der neuen Tabellen posten. Wichtig ist, dass die Strings als utf8mb4 angelegt werden.

**Comment by avollkopf** [comment]
Aber wenn du auf die Index Seite gehst, kannst du bei aktivierten Experteneinstellungen die migration der alten auf die neue strktur automatisch durchführen lassen. Das habe ich implementiert.

**Comment by ollinator2000** [comment]
Ja , mit der Darstellung der Index Seite hatte ich auch so meine Probleme .. 😀 Ich habe ich es aber durch Studium der common_db_settings hinbekommen. 😀  Ich habe das gesamte Konstrukt jetzt in 2 Docker Container verpackt. Das war der Hintergrund meiner ganzen Benühungen. Die tun auch . Soweit ich das bis jetzt getestet habe. Das macht dann eine aufwendige Raspi Installation überflüssig .. ;-)

**Comment by avollkopf** [comment]
ok,
ich habe heute noch einmal ein update des ispindle.py script für python3 hochgeladen. Das läuft.

Dann habe ich mir auch mal einen Container mit Ubuntu 16.04 erstellt, da bisher noch alles auf 14.04 lief. Das läuft jetzt auch.

Ich werde mich dann noch mal an die Doku machen. Der Punkt hier kann ja dann geschlossen werden.
