### ISSUE TITLE
MariaDB instead of Mysql

### ISSUE THREAD

**Issue by GlennFR** [avollkopf/iSpindel-TCP-Server#8]
The install/setup instructions are based around using Mysql, but for Raspian and most other platforms MariaDB is now the preferred sql bundle.  I'm trying to use the current install instructions but there are syntax errors with the CREATE TABLE commands, amongst others...
I think that "Interval" is now a reserved word, for example - and can't be used as a column name.

**Comment by GlennFR** [comment]
OK, my mistake for the reserved words - I hadn't seen the back quotes "\`".  The CREATE command that works is
   CREATE TABLE
    \`Data\` (
    \`Timestamp\` datetime NOT NULL,
    \`Name\` varchar(64) COLLATE ascii_bin NOT NULL,
    \`ID\` int NOT NULL,
    \`Angle\` double NOT NULL,
    \`Temperature\` double NOT NULL,
    \`Battery\` double NOT NULL,
    \`ResetFlag\` boolean,
    \`Gravity\` double NOT NULL DEFAULT 0,
    \`UserToken\` varchar(64) COLLATE ascii_bin,
    \`Interval\` int,
    \`RSSI\` int,
    PRIMARY KEY \`Stamp\` (\`Timestamp\`,\`Name\`,\`ID\`)
) DEFAULT CHARSET=ascii COLLATE=ascii_bin;

Could the install procedures be changed for MariaDB, however ?
Does the Python connector still work, or does the MariaDB version need to be installed (mariadb-connector-python-1.0.2)?
Thanks.

**Comment by avollkopf** [comment]
Hi @GlennFR , my server is running in a ubuntu container environment on my NAS. I am also using MariaDB (10.4.12) but on a different container since I use the DB for several other applications. Therefore I can not write instructions for raspian as I do have currently no pi at hand for the spindle.

**Comment by GlennFR** [comment]
Thanks.  I'll try and document the differences I encounter, perhaps you can include some special notes for pi ?  For the moment I now have the DB created, I'll be working on the Python server next.

**Comment by GlennFR** [comment]
I have the base system working - I'll close this issue.  Thanks.
