### ISSUE TITLE
Incomplete table definitions

### ISSUE THREAD

**Issue by GlennFR** [avollkopf/iSpindel-TCP-Server#9]
There seems to be some difference between the python code "iSpindle.py" and the SQL table definitions in the installation instructions.

- Recipie and Recipie_ID are missing from the "Data" table;

- Archive table is missing.

Please could you provide a complete listing of the up-to-date tables for the current version of iSpindle.py, and a brief description of how Recipie and Archive work.
Thanks

**Comment by avollkopf** [comment]
This should be more or less automatically migrated through the index.php page if you select advanced settings. It is written in the README (New 16.06.2020)

**Comment by GlennFR** [comment]
When I try to use the php web pages, it's stuck 
![Screenshot_2020-10-05_19-39-40](https://user-images.githubusercontent.com/56517031/95113566-f1267f00-0742-11eb-9b4d-bd27b393c851.png)

So I have to manually create the table using the source from setup.php

**Comment by avollkopf** [comment]
1. Did you start with a fresh install?
-> in this case there should be no need to create the tables manually as I created a setup script in php that is automatically started once you call index.php and no database is availalbe. (also writting in the README update 16.06.20)
2. If there was a database incl. data: did you manually modify the data table? -> this sghould be done through trhe script as the database needs to be migrated via the integrated script through the index.php file with advanced settings.

**Comment by wimdm1** [comment]
I have the same problem! The instruction for an update are not clear! In the previous version there were sql files for updating the DB correctly. I dropped the DB and tried launching it again from scratch but this did not work either.

**Comment by avollkopf** [comment]
sql files won't help for the migration from an old database to the new database including the archive as it needs to be created from the exostong data!

Hence it needs to be updated from the index page. If you start from scratch, a setup page should show up and will create the tables This was at least woking on a test system on my side. I can look into the installation from scratch but can' give an ECD as I am currently busy with projects at work. Can you give some mor information on the problems you experienced when starting from scratch.

**Comment by wimdm1** [comment]
I tried it from scratch just created the DB iSpindle and the user iSpindle and after the reboot I tried to connect to the website and I get this message: Table 'iSpindle.Settings' doesn't exist

**Comment by wimdm1** [comment]
![image](https://user-images.githubusercontent.com/35368669/99425278-ec88e500-2902-11eb-92ea-735ea4360a64.png)

**Comment by avollkopf** [comment]
Just try to delete the DB and try to access the index page. If everything is working, the system should reroute you to a page called setup.php

**Comment by wimdm1** [comment]
OK now I get another screen but still some errors:
![image](https://user-images.githubusercontent.com/35368669/99427256-79cd3900-2905-11eb-8ff7-09161d3eb484.png)

**Comment by wimdm1** [comment]
And when I click Save:
![image](https://user-images.githubusercontent.com/35368669/99427447-b862f380-2905-11eb-829d-69888693ff38.png)

**Comment by wimdm1** [comment]
OK I had to grant all privileges to the pi@localhost and now the DB is created and I can continue the config but still with some errors:
![image](https://user-images.githubusercontent.com/35368669/99438401-0bdc3e00-2914-11eb-9cbd-b1a727c7ea16.png)
I restored the missing file common_db_config.php and the Home button image from the previous version and the error was solved:
![image](https://user-images.githubusercontent.com/35368669/99438948-d5eb8980-2914-11eb-9c9b-3e9f2359b5d0.png)

**Comment by avollkopf** [comment]
ok, thanks fro the repsonse. I will update the instructions accordingly. The config file should have been also created but there seems to be an issue with the directory rights. I will look into that and document it also accordingly.

**Comment by avollkopf** [comment]
You should also have a look that the .ini file is being generated for the python scripts. I will need to setup an additional virtual test environment to check the installation from scratch and update the install.md accordingly

**Comment by wimdm1** [comment]
Which ini file do you mean?
I'm not getting any data from my ispindle either. In the previous version this was working well.
It looks like the TCP server is not running on port 9501?
![image](https://user-images.githubusercontent.com/35368669/99517025-30293080-298f-11eb-9079-95afa2ae01b7.png)

**Comment by avollkopf** [comment]
This looks good so far. However, in the config path there is also an iSpindle_default.ini with some default settings for the python scripts. The setup script shuold also create a modified iSpindle_config.ini file with the settings you entered in the setup. If write access to the directory is not working, the script cannot be created. iSpinlde.py is looking for the config file and falls back to the default ini file if the config file is not found. You can either adapt the default file (However, this will be overwritten with every pull) or you create a copy with the other name and put in your settings to access the database.

The script is in  a loop and waiting for the database connection due to the wrong config.

**Comment by avollkopf** [comment]
ok, did a quick and dirty test on a fresh ubuntu container since I have no rasbpi for the spindel. But the basic principle is the same.

The config directory in iSpindel-Srv has to be writable by the apache user (at least during the setup process and creation of the database)

A quick workaround is:
`Cd /home/pi/iSpindel-Srv`
`sudo chown pi:pi config`
`sudo chmod o+w config`

In this case the setup script can create the required files in the config directory.

You can change it back with 
`sudo chmod 755 config`

once the config files have been created.

That should do the trick. 

I will test it in more detail and write a new installations script (However, it is based on my ubuntu system)

**Comment by wimdm1** [comment]
OK I had to go back to the version of 15.10.2008 and now it is working again. Tomorrow I will try to upgrade first to the version 1.63 of 16.06.2019 first and I will let you know how it went.

**Comment by avollkopf** [comment]
ok,

it is also better to change the group of the config directory to the group of the apache user ( in my case e.g. www-data) Then allow the group to write to the config directory:

Change group of config file to apache user group (example www-data)

`sudo chown root:www-data config`

allow write access to config directory for group

`sudo chmod 775 config`

Both files are also created under these conditions

I also tested my demo spindel and it is sending to the test environment.

So far I did no changes to the scripts. Error messages are still displayed in the setup as one file is not available. But I will switch that off in a newer version as it may confuse users.

First thing will be the update of the documentation for a fresh install.

**Comment by wimdm1** [comment]
After 2days of trying it still doesn't work.
There is something I don't understand or can't find anymore in the instructions: How to set up the webserver?
I made a symbolinc link in  to the directory /home/pi/iSpindel-Srv/web
ln -s /home/pi/iSpindel-Srv/web iSpindle
Maybe this is the problem?

**Comment by avollkopf** [comment]
You have to be in the folder of your web server before you run the command:
In my case it is /var/www/html
`cd /var/www/html`
`sudo ln -sf /home/pi/iSpindel-Srv/web/ iSpindle`
`sudo chown -R pi:pi iSpindle/*`
`sudo chown -h pi:pi iSpindle`

**Comment by avollkopf** [comment]
English versions of Readme.md and Install.md have been updated accordingly.
Setup script is now also checking if it has write access to the config path.
Tested a fresh installation on my ubuntu system and it is working.
